<?php

namespace AppBundle\Repository;

/**
 * TennantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TennantRepository extends \Doctrine\ORM\EntityRepository
{
}
